# Generated by Django 2.0.6 on 2019-01-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190113_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Course',
        ),
    ]
