# Generated by Django 2.0.10 on 2019-02-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/images', verbose_name='Imagem'),
        ),
    ]
